
-- create a database -- 
create database KLEBCA;
SHOW DATABASES;

USE KLEBCA;

-- creating a table 

CREATE TABLE TEACHER(
id INT PRIMARY KEY ,
NAME VARCHAR(30),
SUBJECT VARCHAR(30),
SALARY INT
);

-- inserting table values 

INSERT INTO TEACHER
(id , NAME , SUBJECT , SALARY)
VALUES
(23 , "AJAY" , "MATH" , 50000),
(47 , "BHARAT" , "ENGLISH" , 60000),
(18 , "CHETAN" , "CHEMISTRY" , 45000),
(9 , "DIVYA" , "PHYSICS" , 75000); 

SELECT * FROM TEACHER;

TRUNCATE TABLE TEACHER;

DROP TABLE TEACHER;

-- select the teachers whose salary is greater than 55k
SELECT NAME , SALARY FROM TEACHER WHERE SALARY >= 55000;

-- RENAME THE SALARY COLUMN OF TEACHER TABLE TO CTC

ALTER TABLE TEACHER CHANGE COLUMN SALARY CTC INT;
SELECT CTC FROM TEACHER;