-- Create a table to store student information with the following fields:
-- roll_no, name, city, marks

-- Insert the following records into the table:
-- (110, 'adam', 'Delhi', 76)
-- (108, 'bob', 'Mumbai', 65)
-- (124, 'casey', 'Pune', 94)
-- (112, 'duke', 'Pune', 80)

CREATE TABLE STUDENT (
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(30),
CITY VARCHAR(30),
MARKS INT
);

INSERT INTO STUDENT
(ROLL_NO , NAME , CITY , MARKS)
VALUES
(110 , "ADAM" , "DELHI" , 76),
(108 , "BOB" , "MUMBAI" , 65),
(124 , "CASEY" , "PUNE" , 94),
(112 , "DUKE" , "PUNE" , 88);

SELECT * FROM STUDENT;

-- 1. SELECT ALL THE STUDENTS WHO SCORED 75+.
SELECT NAME , MARKS FROM STUDENT WHERE MARKS >= 75;

-- 2. FIND ALL NAMES OF CITIES WHERE THE STUDENTS ARE.
SELECT CITY FROM STUDENT GROUP BY CITY;

-- 3. FIMD THE MAXIMUM MARKS FROM EACH CITY
SELECT MAX(MARKS) , CITY FROM STUDENT GROUP BY CITY;

-- 4. FIND THE AVERAGE MARKS OF THE CLASS
SELECT AVG(MARKS) FROM STUDENT;

-- 5. CREATE A GRADE COLUMN AND ASSIGN THE GRADE BASED ON THE MARKS
-- SET GRADE VALUE "O" IF MARKS >= 80
-- SET GRADE VALUE "A" IF MARKS >= 70 AND MARKS < 80
-- SET GRADE VALUE "B" IF MARKS >= 60 AND MARKS < 70

ALTER TABLE STUDENT 
ADD COLUMN GRADE VARCHAR(30);

UPDATE STUDENT 
SET GRADE = "O"
WHERE MARKS >= 80;

UPDATE STUDENT 
SET GRADE = "A"
WHERE MARKS >= 70 AND MARKS < 80;

UPDATE STUDENT 
SET GRADE = "B"
WHERE MARKS >= 60 AND MARKS < 70;

SELECT * FROM STUDENT;