SELECT @@autocommit;
SET autocommit = 0;

-- creating database and table 


CREATE DATABASE BANK;
USE BANK;
CREATE TABLE BALANCESHEET
(
   ID INT PRIMARY KEY,
   NAME VARCHAR(30),
   BALANCE INT 
);

INSERT INTO BALANCESHEET(
  ID , NAME , BALANCE
) 
VALUES
(126 , "LUFFYTARO" , 14000),
(127 , "ZOROJIRO" , 12000),
(128 , "SANJI" , 10000);


-- TRANSACTIONS
-- Save and commit

SELECT * FROM BALANCESHEET;

START TRANSACTION;

UPDATE BALANCESHEET SET BALANCE = BALANCE - 100 WHERE ID = 126;
UPDATE BALANCESHEET SET BALANCE = BALANCE + 100 WHERE ID = 127;

COMMIT;

START TRANSACTION;

UPDATE BALANCESHEET SET BALANCE = BALANCE - 1000 WHERE ID = 126;
UPDATE BALANCESHEET SET BALANCE = BALANCE + 1000 WHERE ID = 128;

ROLLBACK;

SELECT * FROM BALANCESHEET;

-- SAVEPOINT

START TRANSACTION;

UPDATE BALANCESHEET SET BALANCE = BALANCE + 1000 WHERE ID = 126;
SAVEPOINT AFTER_WALLET_TOPUP;

UPDATE BALANCESHEET SET BALANCE = BALANCE + 10 WHERE ID = 126;
-- ERROR
ROLLBACK TO AFTER_WALLET_TOPUP;

SELECT * FROM BALANCESHEET;
